### ISSUE TITLE
Sequelize migration handling.

### ISSUE THREAD

**Issue by andres-valdes** [hackfiu/peach#12]
So, we've got to make sure that whenever we need to change things in the future we don't need to nuke all our data, so if we could add SQL migrations that would be very nice.

**Comment by andres-valdes** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sequelize migrations](https://trello.com/c/dGM28Df9/1-sequelize-migrations)

**Comment by carloslahrssen** [comment]
Workin on it.

**Comment by carloslahrssen** [comment]
Update: So I got migrations to work however I think we can do some of these things better. Let me know what you guys thinks. [Link to the branch](https://github.com/hackfiu/peach/tree/sequelize-migration)

**Comment by andres-valdes** [comment]
Worked around in #20
