### ISSUE TITLE
Convert database from SQL to MongoDB

### ISSUE THREAD

**Issue by carloslahrssen** [hackfiu/peach#19]
After talking with the team, we decided to move to MongoDB as it would make the user experience much better when it came to changing the model in the future. 

In the case of having a SQL table, we would have to build migrations for those who would want to change Schemas which is a bit of a complicated topic compared to just altering the schema in a mongo document. 

I'll be moving the entire project to Mongo with the ODM package Mongoose in the mongo-feature branch, which I'll publish and update regularly if there's anyone who wants to put in their $0.02.

**Comment by carloslahrssen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Peach] Change peach from SQL with Sequelize to MongoDB with Mongoose](https://trello.com/c/3a07SWIQ/7-peach-change-peach-from-sql-with-sequelize-to-mongodb-with-mongoose)

**Comment by andres-valdes** [comment]
Resolved in #20
