### ISSUE TITLE
Application Update only returns application object when using Postgres

### ISSUE THREAD

**Issue by NSuri1** [hackfiu/peach#6]
Any Sequelize update operation will only return the rows updated if using Postgres and with options.returning set to true. Needs to be worked on if using a different database system.

**Comment by andres-valdes** [comment]
One option is to do a second query for the application that was updated after having updated it, to allow for compatibility with other (lesser) DBMS.

**Comment by andres-valdes** [comment]
Coming to think of it, I think that the second query is the way to go.

Work on this change would be appreciated.

**Comment by andres-valdes** [comment]
Resolved in #11
